@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Apr 20 14:36:23 +0530 2026
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim RiscV_BD_wrapper_tb_behav -key {Behavioral:sim_1:Functional:RiscV_BD_wrapper_tb} -tclbatch RiscV_BD_wrapper_tb.tcl -protoinst "protoinst_files/RiscV_BD.protoinst" -view D:/IIT BOMBAY/SEM 2/DESIGN LAB/COURSE PRPJECT/FINAL_TEST2/syn_ready_with_ila/FINAL_TEST2/FINAL_TEST2.srcs/sim_1/imports/VLSI_RISC_V_IM/RiscV_BD_wrapper_tb_behav.wcfg -log simulate.log"
call xsim  RiscV_BD_wrapper_tb_behav -key {Behavioral:sim_1:Functional:RiscV_BD_wrapper_tb} -tclbatch RiscV_BD_wrapper_tb.tcl -protoinst "protoinst_files/RiscV_BD.protoinst" -view D:/IIT BOMBAY/SEM 2/DESIGN LAB/COURSE PRPJECT/FINAL_TEST2/syn_ready_with_ila/FINAL_TEST2/FINAL_TEST2.srcs/sim_1/imports/VLSI_RISC_V_IM/RiscV_BD_wrapper_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
