# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/RiscV_BD/RiscV_BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD || ORIG_REF_NAME==RiscV_BD} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_Q16_16_Mult_0_0/RiscV_BD_Q16_16_Mult_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_Q16_16_Mult_0_0 || ORIG_REF_NAME==RiscV_BD_Q16_16_Mult_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_register_file_0_0/RiscV_BD_register_file_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_register_file_0_0 || ORIG_REF_NAME==RiscV_BD_register_file_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_csr_0_0/RiscV_BD_csr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_csr_0_0 || ORIG_REF_NAME==RiscV_BD_csr_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_alu_fixed_point_mux_0_0/RiscV_BD_alu_fixed_point_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_alu_fixed_point_mux_0_0 || ORIG_REF_NAME==RiscV_BD_alu_fixed_point_mux_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_csr_mux_0_0/RiscV_BD_csr_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_csr_mux_0_0 || ORIG_REF_NAME==RiscV_BD_csr_mux_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_forwarding_mux_0_0/RiscV_BD_forwarding_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_forwarding_mux_0_0 || ORIG_REF_NAME==RiscV_BD_forwarding_mux_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_load_extend_0_0/RiscV_BD_load_extend_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_load_extend_0_0 || ORIG_REF_NAME==RiscV_BD_load_extend_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_Write_back_Mux_0_0/RiscV_BD_Write_back_Mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_Write_back_Mux_0_0 || ORIG_REF_NAME==RiscV_BD_Write_back_Mux_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_combinational_0_0/RiscV_BD_combinational_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_combinational_0_0 || ORIG_REF_NAME==RiscV_BD_combinational_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_instr_retire_mux_0_0/RiscV_BD_instr_retire_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_instr_retire_mux_0_0 || ORIG_REF_NAME==RiscV_BD_instr_retire_mux_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_concat_2to1_0_0/RiscV_BD_concat_2to1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_concat_2to1_0_0 || ORIG_REF_NAME==RiscV_BD_concat_2to1_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_concat_2to1_1_0/RiscV_BD_concat_2to1_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_concat_2to1_1_0 || ORIG_REF_NAME==RiscV_BD_concat_2to1_1_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_concat_2to1_2_0/RiscV_BD_concat_2to1_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_concat_2to1_2_0 || ORIG_REF_NAME==RiscV_BD_concat_2to1_2_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_or_gate_1_0/RiscV_BD_or_gate_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_or_gate_1_0 || ORIG_REF_NAME==RiscV_BD_or_gate_1_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_alu_muxes_0_2/RiscV_BD_alu_muxes_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_alu_muxes_0_2 || ORIG_REF_NAME==RiscV_BD_alu_muxes_0_2} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_pc_0_0/RiscV_BD_pc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_pc_0_0 || ORIG_REF_NAME==RiscV_BD_pc_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_branch_fsm_0_0/RiscV_BD_branch_fsm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_branch_fsm_0_0 || ORIG_REF_NAME==RiscV_BD_branch_fsm_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_mul_fsm_0_0/RiscV_BD_mul_fsm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_mul_fsm_0_0 || ORIG_REF_NAME==RiscV_BD_mul_fsm_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_IF_ID_PR_0_0/RiscV_BD_IF_ID_PR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_IF_ID_PR_0_0 || ORIG_REF_NAME==RiscV_BD_IF_ID_PR_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_MA_WB_PR_0_0/RiscV_BD_MA_WB_PR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_MA_WB_PR_0_0 || ORIG_REF_NAME==RiscV_BD_MA_WB_PR_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_ALU_OPER_0_0/RiscV_BD_ALU_OPER_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_ALU_OPER_0_0 || ORIG_REF_NAME==RiscV_BD_ALU_OPER_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_controller_0_0/RiscV_BD_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_controller_0_0 || ORIG_REF_NAME==RiscV_BD_controller_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_imm_extend_0_0/RiscV_BD_imm_extend_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_imm_extend_0_0 || ORIG_REF_NAME==RiscV_BD_imm_extend_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_data_mem_0_0/RiscV_BD_data_mem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_data_mem_0_0 || ORIG_REF_NAME==RiscV_BD_data_mem_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_hazard_unit_0_0/RiscV_BD_hazard_unit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_hazard_unit_0_0 || ORIG_REF_NAME==RiscV_BD_hazard_unit_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_two_in32bitmix_0_0/RiscV_BD_two_in32bitmix_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_two_in32bitmix_0_0 || ORIG_REF_NAME==RiscV_BD_two_in32bitmix_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_two_in32bitmix_1_0/RiscV_BD_two_in32bitmix_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_two_in32bitmix_1_0 || ORIG_REF_NAME==RiscV_BD_two_in32bitmix_1_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_ID_EX_PR_0_0/RiscV_BD_ID_EX_PR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_ID_EX_PR_0_0 || ORIG_REF_NAME==RiscV_BD_ID_EX_PR_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_EX_MA_PR_0_0/RiscV_BD_EX_MA_PR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_EX_MA_PR_0_0 || ORIG_REF_NAME==RiscV_BD_EX_MA_PR_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_instr_mem_0_0/RiscV_BD_instr_mem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_instr_mem_0_0 || ORIG_REF_NAME==RiscV_BD_instr_mem_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_apb_soc_top_0_0/RiscV_BD_apb_soc_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_apb_soc_top_0_0 || ORIG_REF_NAME==RiscV_BD_apb_soc_top_0_0} -quiet] -quiet

# IP: bd/RiscV_BD/ip/RiscV_BD_ila_0_0/RiscV_BD_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RiscV_BD_ila_0_0 || ORIG_REF_NAME==RiscV_BD_ila_0_0} -quiet] -quiet

# XDC: d:/IIT BOMBAY/SEM 2/DESIGN LAB/COURSE PRPJECT/FINAL_TEST2/syn_ready_with_ila/FINAL_TEST2/FINAL_TEST2.gen/sources_1/bd/RiscV_BD/ip/RiscV_BD_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==RiscV_BD_ila_0_0 || ORIG_REF_NAME==RiscV_BD_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/IIT BOMBAY/SEM 2/DESIGN LAB/COURSE PRPJECT/FINAL_TEST2/syn_ready_with_ila/FINAL_TEST2/FINAL_TEST2.gen/sources_1/bd/RiscV_BD/ip/RiscV_BD_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==RiscV_BD_ila_0_0 || ORIG_REF_NAME==RiscV_BD_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/IIT BOMBAY/SEM 2/DESIGN LAB/COURSE PRPJECT/FINAL_TEST2/syn_ready_with_ila/FINAL_TEST2/FINAL_TEST2.gen/sources_1/bd/RiscV_BD/ip/RiscV_BD_ila_0_0/RiscV_BD_ila_0_0_ooc.xdc

# XDC: d:/IIT BOMBAY/SEM 2/DESIGN LAB/COURSE PRPJECT/FINAL_TEST2/syn_ready_with_ila/FINAL_TEST2/FINAL_TEST2.gen/sources_1/bd/RiscV_BD/RiscV_BD_ooc.xdc
